### ISSUE TITLE
Update the feature of adding credits

### ISSUE THREAD

**Issue by NidhiGupta23** [NidhiGupta23/CoffeeShop-Demo-using-RestApi#3]
After solving the id functionality we are facing error for updating the credits of particular customer
Error:
Traceback (most recent call last):
  File "C:\Users\ngupta\Min Projects\CoffeeShop-Demo-using-RestApi\src\main.py", line 44, in <module>
    c1.updateMenu()
  File "C:\Users\ngupta\Min Projects\CoffeeShop-Demo-using-RestApi\src\coffeeOrder.py", line 191, in updateMenu
    [loginStatus, loginId] = self.login()
TypeError: cannot unpack non-iterable bool object

**Comment by NidhiGupta23** [comment]
Done. Error is solved by updating the loginId with self.event['cusTd']
